### ISSUE TITLE
[userControllerTests] tests broken

### ISSUE THREAD

**Issue by muceres** [waiter-project/waiter-api#5]
La route /user/register demande la création d'un deviceId.

**Comment by imkh** [comment]
Fixed in https://github.com/waiter-project/waiter-api/commit/4e4a49e532d8f664333d3b2392252ebde1e4260d, https://github.com/waiter-project/waiter-api/commit/e80c10fb1ba72a1b4f3f588eeb5bf2624e55e060, and https://github.com/waiter-project/waiter-api/commit/4e4a49e532d8f664333d3b2392252ebde1e4260d.
